name: Démonstration CI

on: push

jobs:
  Démonstration-CI:
    runs-on: ubuntu-latest
    steps:
      - name: Set up job
        run: echo "Configuration du job"

      - name: Étape 1 - Initialisation
        run: echo "Initialisation en cours"

      - name: Étape 2 - Récupération du code
        uses: actions/checkout@v4

      - name: Étape 3 - Build
        run: echo "Compilation/Build du projet"

      - name: Étape 4 - Tests
        run: echo "Exécution des tests unitaires..."

      - name: Étape 5 - Packaging
        run: echo "Création du package (artifact)..."

      - name: Étape 6 - Fin du pipeline
        run: echo "Pipeline terminé avec succès !"